// <auto-generated />
using System;
using BlackPositivity.Services.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlackPositivity.Services.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190423011227_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlackPositivity.Services.Models.BlackPositivtyQuote", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contributor");

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("Quote");

                    b.Property<bool>("hasBeenUsed");

                    b.HasKey("ID");

                    b.ToTable("BlackPositivityQuote");
                });
#pragma warning restore 612, 618
        }
    }
}
